feat: replace custom-electron-titlebar
organization/alspotron pull request #31
Opened 2023-07-02 23:20 UTC by smnis

* 커스텀 타이틀바 구현
* Window 포커싱이 제대로 안되는 이슈 해결
* macos vibrancy 설정으로 네이티브 블러 적용

2023-07-02 23:35 UTC, Su-Yong requested changes

2023-07-02 23:35 UTC, Su-Yong commented on renderer/components/Titlebar.tsx
> +import { JSX } from 'solid-js/jsx-runtime';
```suggestion
import type { JSX } from 'solid-js/jsx-runtime';
```
타입 import eslint가 뭐라하면 import type으로 해주심 됩니다

2023-07-02 23:35 UTC, Su-Yong commented on renderer/components/Titlebar.tsx
> +  const svgStyle = cx('w-10 h-full p-3 mx-auto')
굳이 따로안빼도 될듯

2023-07-02 23:35 UTC, Su-Yong commented on src/Application.ts
> +      frame: process.platform === 'darwin',
커스텀 타이틀바 윈도우용도 있는거 보니 그냥 false박아도 될듯여

2023-07-02 23:35 UTC, Su-Yong commented on src/Application.ts
> +      frame: process.platform === 'darwin',
ditto

2023-07-02 23:39 UTC, HelloWorld017 approved these changes

2023-07-02 23:57 UTC, smnis commented on src/Application.ts
> +      frame: process.platform === 'darwin',
이건 윈도우보단 macOS쪽이랑 관련있는 부분인데 (macOS는 `titlebarStyle` 때문에 네이티브 traffic light가 적용됨) hyper가 이렇게 했길래 함 넣어봤어본거긴 해요. 근데 별차이 없는 것 같아서 그냥 false로 바꿨슴당

2023-07-03 00:05 UTC, Su-Yong approved these changes

2023-07-03 04:46 UTC, merged